### ISSUE TITLE
servletUnavailableException when accessing a walkaround instance

### ISSUE THREAD

**Issue by GoogleCodeExporter** [strikersix23/walkaround#100]
```
What steps will reproduce the problem?
1. Do a fresh git clone, compile, and upload
2. Go to your app engine url
3. See exception

What is the expected output?  What do you see instead?

The expected output is to see my wave stuff.

Instead, I see:

Uncaught exception from servlet
javax.servlet.UnavailableException: Initialization failed.
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.createHandler(AppVersionHandlerMap.java:211)
    at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.getHandler(AppVersionHandlerMap.java:171)
    at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:123)
    at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:446)
    at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:449)
    at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:455)
    at com.google.tracing.TraceContext.runInContext(TraceContext.java:695)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:333)
    at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:325)
    at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:453)
    at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
    at java.lang.Thread.run(Thread.java:679)

What browser and browser version are you using?  On what operating system?

Newest Firefox for OSX 10.6.8 and Chrome 18 both show the error, along with 
Firefox 11 on a Windows 7 box.

What URL does your browser show when the problem occurs?  Did you compile
walkaround on your machine, or are you using a public instance?

https://kwalkaround.appspot.com/

I compiled it on my Mac OSX 10.6.8 macbook pro and then deployed to google app 
engine.

Please provide any additional information below.

I saw the error on my full-text-search walkaround instance that had been 
running just fine for 8 days. I decided to do a fresh git clone, compile, and 
deploy. When I tried to compile, I had to tweak line 473 in WaveIndexer.java (a 
parentheses issue) to get it to compile. It ran fine at "localhost:8080", but 
when I deployed the newly compiled instance, I got the same exception I had 
before.
```

Original issue reported on code.google.com by `otter...@gmail.com` on 19 Apr 2012 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
Just wanted to make clear that I am only seeing any of the above problems 
(including the compiling issue) with a full-text-search version of walkaround. 
I have reverted to a non-full-text-search-version for the moment.
```

Original comment by `otter...@gmail.com` on 19 Apr 2012 at 4:15

**Comment by GoogleCodeExporter** [comment]
```
I think "Initialization failed" means that walkaround failed to start up, and 
that there's another error message in the logs that says why.  Can you look in 
the logs for that other message?
```

Original comment by `oh...@google.com` on 19 Apr 2012 at 6:05

**Comment by GoogleCodeExporter** [comment]
```
I attached one expanded entry in my logs. Here is that entry unexpanded:

2012-04-18 21:25:50.794 / 500 670ms 0kb Mozilla/5.0 (Macintosh; Intel Mac OS X 
10.7; rv:11.0) Gecko/20100101 Firefox/11.0
I 2012-04-18 21:25:50.690 com.google.inject.internal.MessageProcessor visit: An 
exception was caught and reported. Message: java.lang.ClassNotFoundException: 
com.google.appengi
W 2012-04-18 21:25:50.790 Failed startup of context 
com.google.apphosting.utils.jetty.RuntimeAppEngineWebAppContext@1117cc0{/,/base/
data/home/apps/s~kwalkaround/1.3583090799615
W 2012-04-18 21:25:50.790 <continued from previous message> Caused by: 
com.google.inject.internal.util.$ComputationException: 
com.google.inject.internal.util.$ComputationExcept
W 2012-04-18 21:25:50.790 <continued from previous message> at 
com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853
) at com.google.inject.internal.
W 2012-04-18 21:25:50.790 <continued from previous message> Caused by: 
java.lang.ClassNotFoundException: com.google.appengine.api.search.IndexManager 
at com.google.appengine.r
C 2012-04-18 21:25:50.792 Uncaught exception from servlet 
javax.servlet.UnavailableException: Initialization failed. at 
com.google.apphosting.runtime.jetty.AppVersionHandlerMa

```

Original comment by `otter...@gmail.com` on 19 Apr 2012 at 7:19

Attachments:
- [WalkaroundErrorLog.txt](https://storage.googleapis.com/google-code-attachments/walkaround/issue-100/comment-3/WalkaroundErrorLog.txt)

**Comment by GoogleCodeExporter** [comment]
```
Thanks.  Looks like the full text search API has changed incompatibly, so the 
code no longer works.  I'll look into moving the code to the new API.

```

Original comment by `oh...@google.com` on 19 Apr 2012 at 8:58
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in 
http://code.google.com/p/walkaround/source/detail?r=8e66aa2924011a10d13d90cc58ef
2520fc28d25b .
```

Original comment by `oh...@google.com` on 19 Apr 2012 at 10:56
- Changed state: **Fixed**
