### ISSUE TITLE
/taskqueue/postcommit doesn't work - 100% errors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [strikersix23/walkaround#110]
```
Here is the log:

I 2012-05-23 21:57:31.917
com.google.walkaround.wave.server.servlet.ServerExceptionFilter sendError: 
Trust status: UNTRUSTED
E 2012-05-23 21:57:31.917
com.google.walkaround.wave.server.servlet.ServerExceptionFilter sendError: 
NoSuchMethodError; overQuota=false; sending 500: Internal server error
java.lang.NoSuchMethodError: 
com.google.appengine.api.search.Index.add([Lcom/google/appengine/api/search/Docu
ment;)Lcom/google/appengine/api/search/AddDocumentsResponse;
    at com.google.walkaround.wave.server.index.WaveIndexer.index(WaveIndexer.java:473)
    at com.google.walkaround.wave.server.index.WaveIndexer.indexConversation(WaveIndexer.java:305)
    at com.google.walkaround.wave.server.index.IndexTask$Conv$1.run(IndexTask.java:67)
    at com.google.walkaround.util.server.RetryHelper$3.run(RetryHelper.java:182)
    at com.google.walkaround.util.server.RetryHelper$3.run(RetryHelper.java:180)
```

Original issue reported on code.google.com by `vega113` on 24 May 2012 at 5:00

**Comment by GoogleCodeExporter** [comment]
```
Should be fixed in 
http://code.google.com/p/walkaround/source/detail?r=fe81869222db3af0c8cc88f304c2
5121c15d4823 .

Please run the re-indexing mapreduce after deploying this.
```

Original comment by `ohl...@gmail.com` on 25 May 2012 at 8:15
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
I get this compilation error after pulling:


compile:
    [javac] Compiling 196 source files to /home/vega/walkaround/build/server
    [javac] WaveIndexer.java:473: incompatible types
    [javac] found   : com.google.appengine.api.search.AddDocumentsResponse
    [javac] required: com.google.appengine.api.search.AddResponse
    [javac]       resp = idx.add(doc);
    [javac]                     ^
    [javac] 1 error

BUILD FAILED

```

Original comment by `vega113` on 26 May 2012 at 7:26

**Comment by GoogleCodeExporter** [comment]
```
Ok, solved it. Had to run ./get-third-party-deps after switching to 
full-text-search branch.
```

Original comment by `vega113` on 26 May 2012 at 8:07
