### ISSUE TITLE
redirect loop when enabling user names and pictures

### ISSUE THREAD

**Issue by GoogleCodeExporter** [strikersix23/walkaround#25]
```
What steps will reproduce the problem?
1. Install an instance to App Engine following the instructions at 
http://code.google.com/p/walkaround/wiki/RunningTheCode, also add the client 
API keys
2. Click Enable user names and pictures, click Enable

What is the expected output?  What do you see instead?
A popup should appear to connect to my Google Account. Instead, I get a 
redirect loop error

What browser and browser version are you using?  On what operating system?
Chrome 17.0.963.2 dev on Ubuntu 10.10

What URL does your browser show when the problem occurs?  Did you compile
walkaround on your machine, or are you using a public instance?
https://agrobrokerwave.appspot.com/authenticate?code=<lot's of 
characters>&tryagain=true
It's running on google app engine

Please provide any additional information below.
I've been using the latest commit, 9fea999d779ea4a21fbc6a2eb5f660a71a2c6a7e
```

Original issue reported on code.google.com by `mesterad...@gmail.com` on 12 Dec 2011 at 12:19

**Comment by GoogleCodeExporter** [comment]
```
I think 
http://googlecode.blogspot.com/2011/10/upcoming-changes-to-oauth-20-endpoint.htm
l broke us, please see if my latest commit fixes it (it does for me).
```

Original comment by `oh...@google.com` on 12 Dec 2011 at 6:21
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
yup it works now, thanks :)
```

Original comment by `mesterad...@gmail.com` on 12 Dec 2011 at 6:58

**Comment by GoogleCodeExporter** [comment]
```
I'm now getting this redirect loop.  I've downloaded the code on a fresh linux 
vm (on Dec 26th) and recompiled/deployed.  But I still get: Error 310 
(net::ERR_TOO_MANY_REDIRECTS): There were too many redirects.

I'm using Chrome 16.0.912.63 m on Windows 7, but it happens on multiple 
computers with multiple Google accounts.

The URL the pop is displaying in the error text is:
https://scalesofwave.appspot.com/authenticate?code=<complex alpha 
code>&tryagain=true
```

Original comment by `AJFr...@gmail.com` on 28 Dec 2011 at 1:47

**Comment by GoogleCodeExporter** [comment]
```
In 
https://groups.google.com/group/walkaround-dev/browse_thread/thread/f08808333983
1e5d/6f3fce485d70cee9 , this was caused by an incorrect client secret setting.  
Please check your runant script.
```

Original comment by `oh...@google.com` on 28 Dec 2011 at 6:29

**Comment by GoogleCodeExporter** [comment]
```
Funny enough it wasn't the secret, it was the Client ID.  I removed the 
".apps.googleusercontent.com" from it, leaving only the number and 
reran/uploaded.  Now it works.

The instructions at http://code.google.com/p/walkaround/wiki/RunningTheCode 
just say to "copy and paste"  so I did.  Perhaps they should be made more 
clear?  Or maybe I'm just dense...
```

Original comment by `AJFr...@gmail.com` on 29 Dec 2011 at 7:07

**Comment by GoogleCodeExporter** [comment]
```
That's strange.  It works for me with the suffix.  Are you sure this is the 
only change that you made?  What did the server logs say during the redirect 
loop?
```

Original comment by `oh...@google.com` on 29 Dec 2011 at 7:37

**Comment by GoogleCodeExporter** [comment]
```
That's the only change...  I think this is the error from the same timestamp:

com.google.walkaround.wave.server.rpc.ClientExceptionHandler handleData: 
[client:1324584609460] Class$pc: (TypeError): Cannot read property 'appengine' 
of undefined
com.google.walkaround.wave.server.rpc.ClientExceptionHandler$ClientException: 
(com.google.gwt.core.client.JavaScriptException?) (TypeError): Cannot read 
property 'appengine' of undefined
    at com.google.gwt.core.client.impl.StackTraceCreator$CollectorEmulated.$fillInStackTrace(StackTraceCreator.java:162)
    at java.lang.Throwable.fillInStackTrace(Throwable.java:71)
    at com.google.gwt.core.client.JavaScriptException.JavaScriptException(JavaScriptException.java:106)
    at com.google.gwt.lang.Exceptions.caught(Exceptions.java:25)
    at com.google.walkaround.wave.client.GaeChannelDemuxer.$connectNative(GaeChannelDemuxer.java:87)
    at com.google.walkaround.wave.client.GaeChannelDemuxer.$connect(GaeChannelDemuxer.java:77)
    at com.google.walkaround.wave.client.GaeReceiveOpChannel.$connect(GaeReceiveOpChannel.java:149)
    at com.google.walkaround.slob.client.GenericOperationChannel.$connect(GenericOperationChannel.java:312)
    at com.google.walkaround.wave.client.WalkaroundOperationChannel.$setListener(WalkaroundOperationChannel.java:179)
    at org.waveprotocol.wave.concurrencycontrol.wave.OperationSucker.start(OperationSucker.java:66)
    at com.google.walkaround.wave.client.Walkaround$2$2$4.$connectWavelet(Walkaround.java:364)
    at com.google.walkaround.wave.client.Walkaround$2$2$4.$connect(Walkaround.java:415)
    at org.waveprotocol.wave.client.StageTwo$DefaultProvider.$install(StageTwo.java:678)
    at org.waveprotocol.wave.client.StageTwo$DefaultProvider$1.$execute(StageTwo.java:246)
    at org.waveprotocol.wave.client.common.util.CountdownLatch.$tick(CountdownLatch.java:60)
    at org.waveprotocol.wave.client.StageTwo$DefaultProvider$3.execute(StageTwo.java:264)
    at org.waveprotocol.wave.client.scheduler.BrowserBackedScheduler.$workUnit(BrowserBackedScheduler.java:261)
    at org.waveprotocol.wave.client.scheduler.BrowserBackedScheduler.$workAll(BrowserBackedScheduler.java:314)
    at org.waveprotocol.wave.client.scheduler.BrowserBackedScheduler.$workSlice(BrowserBackedScheduler.java:346)
    at org.waveprotocol.wave.client.scheduler.BrowserBackedScheduler$1.$run(BrowserBackedScheduler.java:38)
    at org.waveprotocol.wave.client.scheduler.GwtSimpleTimer$2.run(GwtSimpleTimer.java:45)
    at com.google.gwt.user.client.Timer.fire(Timer.java:141)
    at UNKNOWN_CLASS.anonymous(UNKNOWN_FILE:0)
    at com.google.gwt.core.client.impl.Impl.apply(Impl.java:165)
    at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:196)
    at UNKNOWN_CLASS.anonymous(UNKNOWN_FILE:0)


```

Original comment by `AJFr...@gmail.com` on 29 Dec 2011 at 7:50

**Comment by GoogleCodeExporter** [comment]
```
That error is unrelated.  It should be something involving "Failed attempt, 
trying again", "content of rejected request", and "rejection response body".

```

Original comment by `oh...@google.com` on 29 Dec 2011 at 8:23

**Comment by GoogleCodeExporter** [comment]
```
A note to anyone else experiencing mad redirect loops:  Change your appengine 
authentication settings from Federated (Experimental) to Google Accounts api, 
and the loop goes away.  In order to support federated openID, it will likely 
be necessary to create a landing page for users to select the account they wish 
to login to...
```

Original comment by `internetparty@wetheinter.net` on 2 Apr 2012 at 1:02
